name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
            yarn install --immutable
          elif [ -e pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Verify formatting
        run: yarn format

      - name: Perform linting
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
            yarn install --immutable
          elif [ -e pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Run build
        env:
          BUILD_ID: ${{ github.sha }}
          SITE_URL: https://tyrrrz.me
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATREON_TOKEN: ${{ secrets.PATREON_TOKEN }}
          BUYMEACOFFEE_TOKEN: ${{ secrets.BUYMEACOFFEE_TOKEN }}
          PRIVATE_DONORS: ${{ secrets.PRIVATE_DONORS }}
        run: yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: dist

  deploy:
    if: ${{ github.event_name != 'pull_request' }}

    needs:
      - format
      - build

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
