name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.VERCEL_WEBHOOK }}
          method: POST
