name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        uses: tyrrrz/action-http-request@v1
        with:
          url: ${{ secrets.VERCEL_WEBHOOK }}
          method: POST
