name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write

    steps:
      - name: Trigger build and deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh workflow run main.yml --repo "$GH_REPO"
