name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Trigger deploy
        uses: tyrrrz/action-http-request@25f132e48dea89c0f6b7955398270b506e1d51cb # 1.1.4
        with:
          url: ${{ secrets.VERCEL_WEBHOOK }}
          method: POST
          retry-count: 5
