name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        uses: tyrrrz/action-http-request@66a047c7508f4418114d1080fbfc348621cdc78f # 1.1.0
        with:
          url: ${{ secrets.VERCEL_WEBHOOK }}
          method: POST
          retry-count: 5
