name: redeploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Trigger deploy
        uses: tyrrrz/action-http-request@1dd7ad841a34b9299f3741f7c7399f9feefdfb08 # 1.1.3
        with:
          url: ${{ secrets.VERCEL_WEBHOOK }}
          method: POST
          retry-count: 5
